import { useEffect, useState } from 'react'
import { api } from '../api/api'
import type { Recommendation } from '../types'
import { useAuth } from '../auth/useAuth'
import { Button, Card, Notice, PageHeader, StatusPill } from '../components/Ui'

export function BriefPage() {
  const { can } = useAuth(); const [brief, setBrief] = useState<Recommendation | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [feedback, setFeedback] = useState('')
  const load = () => { setLoading(true); setError(''); api.recommendations().then(r => setBrief(r.items[0] ?? null)).catch(e => setError(e instanceof Error ? e.message : 'Unable to load briefs')).finally(() => setLoading(false)) }
  useEffect(load, [])
  const generate = async () => { setBusy(true); setError(''); setSuccess(''); try { setBrief(await api.generateBrief()); setSuccess('Brief generated successfully.') } catch (e) { setError(e instanceof Error ? e.message : 'Brief generation failed') } finally { setBusy(false) } }
  const update = async (action: 'approve' | 'reject') => { if (!brief) return; setError(''); setSuccess(''); try { setBrief(await api.briefAction(brief.id, action)); setSuccess(`Brief ${action === 'approve' ? 'approved' : 'rejected'}.`) } catch (e) { setError(e instanceof Error ? e.message : 'Brief action failed') } }
  const saveFeedback = async () => { if (!brief || !feedback.trim()) { setError('Feedback cannot be empty.'); return }; setError(''); setSuccess(''); try { setBrief(await api.feedback(brief.id, feedback.trim())); setFeedback(''); setSuccess('Feedback saved.') } catch (e) { setError(e instanceof Error ? e.message : 'Feedback failed') } }
  return <><PageHeader eyebrow="Decision support" title="AI operations brief" description="A provider response is always grounded in selected risk-event evidence. Rule-based output is labelled explicitly when AI is unavailable." action={can('ADMIN', 'MANAGER') && <Button onClick={() => void generate()} busy={busy}>Generate brief</Button>} />{error && <Notice>{error}</Notice>}{success && <Notice tone="info">{success}</Notice>}{loading ? <Card><div className="skeleton h-40 w-full" /></Card> : !brief ? <Card><p className="text-sm text-slate-400">No brief has been generated yet.</p></Card> : <div className="space-y-5"><Card><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><StatusPill value={brief.generatedBy} /><StatusPill value={brief.status} /></div><span className="text-xs text-slate-400">{brief.modelProviderName} / prompt {brief.promptVersion}</span></div><h2 className="mt-5 text-xl font-semibold text-white">{brief.summary}</h2><div className="mt-6 space-y-3">{brief.actions.map(action => <div key={`${action.riskEventId}-${action.action}`} className="rounded-xl bg-slate-900/70 p-4"><div className="flex items-center justify-between gap-3"><p className="font-medium text-slate-100">{action.action}</p><StatusPill value={action.priority} /></div><p className="mt-2 text-xs text-slate-400">Risk {action.riskEventId.slice(0, 8)}...</p></div>)}</div>{can('ADMIN', 'MANAGER') && brief.status === 'GENERATED' && <div className="mt-6 flex gap-2"><Button onClick={() => void update('approve')}>Approve</Button><Button variant="danger" onClick={() => void update('reject')}>Reject</Button></div>}</Card><Card><h2 className="font-semibold text-white">Operator feedback</h2><textarea aria-label="Brief feedback" maxLength={2000} value={feedback} onChange={e => setFeedback(e.target.value)} className="field mt-3 min-h-24" placeholder="What was useful or missing?" />{can('ADMIN', 'MANAGER') && <Button variant="secondary" className="mt-3" onClick={() => void saveFeedback()}>Save feedback</Button>}</Card></div>}</>
}

