import { useCallback, useEffect, useState } from 'react'
import { api } from '../api/api'
import type { Risk } from '../types'
import { useAuth } from '../auth/useAuth'
import { Button, Card, Notice, PageHeader, Pagination, StatusPill } from '../components/Ui'

const sortOptions = [['createdAt,desc', 'Newest'], ['createdAt,asc', 'Oldest'], ['severity,desc', 'Severity'], ['riskType,asc', 'Risk type'], ['status,asc', 'Status']] as const
const actionLabels = { acknowledge: 'acknowledged', resolve: 'resolved', dismiss: 'dismissed' } as const

export function RisksPage() {
  const { can } = useAuth()
  const [items, setItems] = useState<Risk[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(''); const [page, setPage] = useState(0); const [size, setSize] = useState(20); const [totalPages, setTotalPages] = useState(0); const [severity, setSeverity] = useState(''); const [status, setStatus] = useState(''); const [riskType, setRiskType] = useState(''); const [entityType, setEntityType] = useState(''); const [entityId, setEntityId] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [sort, setSort] = useState('createdAt,desc')
  const load = useCallback(() => { setLoading(true); setError(''); api.risks({ page, size, sort, severity: severity || undefined, status: status || undefined, riskType: riskType || undefined, entityType: entityType || undefined, entityId: entityId || undefined, from: from ? `${from}T00:00:00Z` : undefined, to: to ? `${to}T23:59:59Z` : undefined }).then(response => { setItems(response.items); setTotalPages(response.totalPages) }).catch(e => setError(e instanceof Error ? e.message : 'Unable to load risks')).finally(() => setLoading(false)) }, [page, size, sort, severity, status, riskType, entityType, entityId, from, to])
  useEffect(() => { load() }, [load])
  const action = async (id: string, name: 'acknowledge' | 'resolve' | 'dismiss') => { setBusy(id); setError(''); setSuccess(''); try { const updated = await api.riskAction(id, name); setItems(current => current.map(item => item.id === id ? updated : item)); setSuccess(`Risk ${actionLabels[name]} successfully.`) } catch (e) { setError(e instanceof Error ? e.message : 'Risk action failed') } finally { setBusy('') } }
  const scan = async () => { setBusy('scan'); setError(''); setSuccess(''); try { const result = await api.scanRisks(); setSuccess(`Scan complete: ${result.createdRiskEvents} new risk event(s).`); setPage(0) } catch (e) { setError(e instanceof Error ? e.message : 'Risk scan failed') } finally { setBusy('') } }
  const clearFilters = () => { setSeverity(''); setStatus(''); setRiskType(''); setEntityType(''); setEntityId(''); setFrom(''); setTo(''); setSort('createdAt,desc'); setPage(0) }
  const resetPage = (setter: (value: string) => void) => (value: string) => { setter(value); setPage(0) }
  return <>
    <PageHeader eyebrow="Signals" title="Risk events" description="Review deterministic evidence, then acknowledge or resolve only when the operating state supports it." action={can('ADMIN', 'MANAGER') && <Button busy={busy === 'scan'} onClick={() => void scan()}>Run scan</Button>} />
    {error && <Notice>{error}</Notice>}{success && <Notice tone="info">{success}</Notice>}
    <Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm text-slate-300">Severity<select aria-label="Filter severity" value={severity} onChange={e => resetPage(setSeverity)(e.target.value)} className="field mt-2"><option value="">All severities</option>{['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map(value => <option key={value}>{value}</option>)}</select></label>
      <label className="text-sm text-slate-300">Status<select aria-label="Filter status" value={status} onChange={e => resetPage(setStatus)(e.target.value)} className="field mt-2"><option value="">All statuses</option>{['OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED'].map(value => <option key={value}>{value}</option>)}</select></label>
      <label className="text-sm text-slate-300">Risk type<select aria-label="Filter risk type" value={riskType} onChange={e => resetPage(setRiskType)(e.target.value)} className="field mt-2"><option value="">All risk types</option>{['STOCKOUT_RISK', 'OVERSTOCK_RISK', 'SLOW_MOVING_INVENTORY', 'ORDER_DELAY_RISK', 'SUPPLIER_DELAY_RISK', 'LOW_MARGIN_RISK'].map(value => <option key={value}>{value.replaceAll('_', ' ')}</option>)}</select></label>
      <label className="text-sm text-slate-300">Entity type<select aria-label="Filter entity type" value={entityType} onChange={e => resetPage(setEntityType)(e.target.value)} className="field mt-2"><option value="">All entities</option>{['PRODUCT', 'ORDER', 'SUPPLIER'].map(value => <option key={value}>{value}</option>)}</select></label>
      <label className="text-sm text-slate-300">Entity ID<input aria-label="Filter entity ID" value={entityId} onChange={e => setEntityId(e.target.value)} className="field mt-2" placeholder="UUID" /></label>
      <label className="text-sm text-slate-300">From<input aria-label="Filter from date" type="date" value={from} onChange={e => resetPage(setFrom)(e.target.value)} className="field mt-2" /></label>
      <label className="text-sm text-slate-300">To<input aria-label="Filter to date" type="date" value={to} onChange={e => resetPage(setTo)(e.target.value)} className="field mt-2" /></label>
      <label className="text-sm text-slate-300">Sort<select aria-label="Sort risks" value={sort} onChange={e => resetPage(setSort)(e.target.value)} className="field mt-2">{sortOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
    </div><div className="mt-4 flex gap-2"><Button variant="secondary" onClick={clearFilters}>Clear filters</Button><Button variant="secondary" onClick={load}>Refresh</Button></div></Card>
    <Card className="mt-5">{loading ? <div className="skeleton h-40 w-full" /> : items.length === 0 ? <p className="py-12 text-center text-sm text-slate-400">No risk events match these filters.</p> : <div className="space-y-3">{items.map(item => <article key={item.id} className="rounded-xl border border-slate-800 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><StatusPill value={item.severity} /><StatusPill value={item.status} /><span className="text-xs text-slate-400">{item.riskType.replaceAll('_', ' ')}</span></div><h2 className="mt-2 font-medium text-white">{item.explanation}</h2><p className="mt-1 text-sm text-slate-400">{item.recommendedAction}</p></div>{can('ADMIN', 'MANAGER') && <div className="flex shrink-0 gap-2">{item.status === 'OPEN' && <Button busy={busy === item.id} variant="secondary" onClick={() => void action(item.id, 'acknowledge')}>Acknowledge</Button>}{(item.status === 'OPEN' || item.status === 'ACKNOWLEDGED') && <><Button busy={busy === item.id} variant="secondary" onClick={() => void action(item.id, 'resolve')}>Resolve</Button><Button busy={busy === item.id} variant="danger" onClick={() => void action(item.id, 'dismiss')}>Dismiss</Button></>}</div>}</div><div className="mt-3 text-xs text-slate-400">Evidence captured {new Date(item.createdAt).toLocaleString()} / {item.entityType} {item.entityId.slice(0, 8)}...</div></article>)}</div>}<Pagination page={page} totalPages={totalPages} onPageChange={setPage} size={size} onSizeChange={nextSize => { setSize(nextSize); setPage(0) }} /></Card>
  </>
}

