import { FormEvent, useEffect, useState } from 'react'
import { api } from '../api/api'
import type { Supplier, SupplierInput } from '../types'
import { useAuth } from '../auth/useAuth'
import { Button, Card, Notice, PageHeader, StatusPill } from '../components/Ui'

const emptyDraft: SupplierInput = { name: '', contactInfo: { email: '' }, averageLeadTimeDays: 0, expectedSlaDays: 0 }

export function SuppliersPage() {
  const { can } = useAuth(); const [items, setItems] = useState<Supplier[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [draft, setDraft] = useState<SupplierInput>(emptyDraft)
  useEffect(() => { api.suppliers().then(r => setItems(r.items)).catch(e => setError(e instanceof Error ? e.message : 'Unable to load suppliers')).finally(() => setLoading(false)) }, [])
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); setSuccess(''); try { const created = await api.createSupplier(draft); setItems(current => [created, ...current]); setDraft(emptyDraft); setShowForm(false); setSuccess(`Supplier ${created.name} created.`) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create supplier') } finally { setSaving(false) } }
  const deactivate = async (item: Supplier) => { setError(''); setSuccess(''); try { await api.deactivateSupplier(item.id, item.version); setItems(current => current.map(row => row.id === item.id ? { ...row, active: false } : row)); setSuccess(`Supplier ${item.name} deactivated.`) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to deactivate supplier') } }
  return <><PageHeader eyebrow="Partners" title="Suppliers" description="Keep lead time and service-level context close to purchasing decisions." action={can('ADMIN', 'OPERATOR') && <Button onClick={() => { setShowForm(value => !value); setSuccess('') }}>{showForm ? 'Close form' : 'New supplier'}</Button>} />{error && <Notice>{error}</Notice>}{success && <Notice tone="info">{success}</Notice>}{showForm && <Card className="mb-5"><h2 className="font-semibold text-white">Create supplier</h2><form onSubmit={save} className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-300">Name<input required value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} className="field mt-2" /></label><label className="text-sm text-slate-300">Email<input type="email" value={draft.contactInfo?.email ?? ''} onChange={e => setDraft({ ...draft, contactInfo: { ...draft.contactInfo, email: e.target.value } })} className="field mt-2" /></label><label className="text-sm text-slate-300">Average lead time (days)<input min="0" step="0.1" type="number" value={draft.averageLeadTimeDays ?? 0} onChange={e => setDraft({ ...draft, averageLeadTimeDays: Number(e.target.value) })} className="field mt-2" /></label><label className="text-sm text-slate-300">Expected SLA (days)<input required min="0" type="number" value={draft.expectedSlaDays} onChange={e => setDraft({ ...draft, expectedSlaDays: Number(e.target.value) })} className="field mt-2" /></label><div><Button type="submit" busy={saving}>Create supplier</Button></div></form></Card>}<Card>{loading ? <div className="skeleton h-40 w-full" /> : items.length === 0 ? <p className="py-12 text-center text-sm text-slate-400">No suppliers found.</p> : <div className="overflow-x-auto"><table className="data-table"><caption className="sr-only">Suppliers</caption><thead><tr><th scope="col">Supplier</th><th scope="col">Lead time</th><th scope="col">Expected SLA</th><th scope="col">Status</th>{can('ADMIN') && <th scope="col">Actions</th>}</tr></thead><tbody>{items.map(item => <tr key={item.id}><td className="font-medium text-white">{item.name}</td><td>{item.averageLeadTimeDays} days</td><td>{item.expectedSlaDays} days</td><td><StatusPill value={item.active ? 'ACTIVE' : 'INACTIVE'} /></td>{can('ADMIN') && <td>{item.active && <Button variant="danger" onClick={() => void deactivate(item)}>Deactivate</Button>}</td>}</tr>)}</tbody></table></div>}</Card></>
}

