import { expect, test } from '@playwright/test'

test('mock console covers login, dashboard, products, risks, brief, and logout', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('Email').fill('manager@example.test')
  await page.getByLabel('Password').fill('demo-password')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page.getByText('Operations at a glance')).toBeVisible()

  await page.getByRole('link', { name: 'Products' }).click()
  await expect(page.getByRole('heading', { name: 'Products' })).toBeVisible()
  await page.getByRole('link', { name: 'Orders', exact: true }).click()
  await page.getByRole('button', { name: 'New order' }).click()
  await page.getByLabel('Order number').fill('ORD-1002')
  await page.getByLabel('Customer').fill('Demo Retail')
  await page.getByLabel('Expected ship date').fill('2026-07-25')
  await page.getByLabel('Order product').selectOption('product-1')
  await page.getByLabel('Quantity').fill('2')
  await page.getByLabel('Unit price').fill('12')
  await page.getByRole('button', { name: 'Create order' }).click()
  await expect(page.getByText('Order ORD-1002 created.')).toBeVisible()
  await page.getByRole('link', { name: 'Purchase orders' }).click()
  await page.getByRole('button', { name: 'New purchase order' }).click()
  await page.getByLabel('PO number').fill('PO-2002')
  await page.getByLabel('Purchase order supplier').selectOption('supplier-1')
  await page.getByLabel('Expected delivery date').fill('2026-07-30')
  await page.getByLabel('Purchase order product').selectOption('product-1')
  await page.getByLabel('Quantity').fill('3')
  await page.getByLabel('Unit cost').fill('8')
  await page.getByRole('button', { name: 'Create purchase order' }).click()
  await expect(page.getByText('Purchase order PO-2002 created.')).toBeVisible()
  await page.getByRole('link', { name: 'Risk events' }).click()
  await expect(page.getByRole('heading', { name: 'Risk events' })).toBeVisible()
  await page.getByRole('combobox', { name: 'Rows per page' }).selectOption('1')
  await expect(page.getByText('Page 1 of 3')).toBeVisible()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByText('Page 2 of 3')).toBeVisible()
  await page.getByRole('link', { name: 'AI brief' }).click()
  await expect(page.getByRole('heading', { name: 'AI operations brief' })).toBeVisible()
  await page.getByRole('button', { name: 'Generate brief' }).click()
  await expect(page.getByText('RULE_BASED')).toBeVisible()
  await page.getByRole('button', { name: 'Approve' }).click()
  await expect(page.getByText('APPROVED', { exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'Reports' }).click()
  await expect(page.getByRole('heading', { name: 'Reports' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Inventory risk' })).toBeVisible()
  await page.getByRole('tab', { name: 'Product margin' }).click()
  await expect(page.getByRole('heading', { name: 'Product margin' })).toBeVisible()

  await page.getByRole('link', { name: 'Imports' }).click()
  await expect(page.getByRole('heading', { name: 'Imports' })).toBeVisible()
  await page.getByLabel('CSV file').setInputFiles({ name: 'products.csv', mimeType: 'text/csv', buffer: Buffer.from('sku,name,safetyStock,reorderPoint,cost,sellingPrice\nSKU-NEW,New Widget,2,3,1,2') })
  await page.getByRole('button', { name: 'Start import' }).click()
  await expect(page.getByText(/Import .* accepted\./)).toBeVisible()
  await expect(page.getByText('COMPLETED')).toBeVisible({ timeout: 5000 })

  await page.getByRole('button', { name: 'Sign out' }).last().click()
  await expect(page.getByRole('heading', { name: 'Make the next move obvious.' })).toBeVisible()
})
